name: suqk

channels:
  - conda-forge

dependencies:
  - python=3.14
  # needed for qforte
  - openblas
  - psi4
  - cmake
  - pytest
  # needed for qiskit
  - qiskit
  - qiskit-aer
  - qiskit-ibm-runtime
  - qiskit-qasm3-import
  - openfermion
  # needed for jupyter notebooks
  - jupyterlab
